[package]
name = "mv64e-mtb-dto"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Paul-Christian Volkmer <code@pcvolkmer.de>"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
