name: 'Check Compatibility'

on:
  schedule:
    - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # See: https://github.com/KohlbacherLab/dnpm-dip-api-gateway/blob/main/app/controllers/README.md#synthetic-json-data
      - name: Download synthetic mtb patient record
        run: curl -f -L https://preview.dnpm-dip.net/api/mtb/fake/data/patient-record -o ./tests/mv64e-mtb-fake-patient.json
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose